### ISSUE TITLE
Building with zig 0.15.1 gives error

### ISSUE THREAD

**Issue by Ippokratis** [MoAlyousef/zfltk#40]
Hi, I hope you are doing well.
Working on a Mac M2 with Sequoia 15.6.1, I am using zig 0.15.1.
zig build gives the following :

```
build.zig:124:18: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
                .root_source_file = b.path(ex.input),
                 ^~~~~~~~~~~~~~~~
/Users/macbookuser/.cache/zig/p/N-V-__8AAOhRdxXO9Cihbi8hyw61uvwoR09-u3NOSGOtr5uh/lib/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_21144: /Users/macbookuser/.cache/zig/p/N-V-__8AAOhRdxXO9Cihbi8hyw61uvwoR09-u3NOSGOtr5uh/lib/std/Build.zig:2215:44
    main: /Users/macbookuser/.cache/zig/p/N-V-__8AAOhRdxXO9Cihbi8hyw61uvwoR09-u3NOSGOtr5uh/lib/compiler/build_runner.zig:366:29
    4 reference(s) hidden; use '-freference-trace=6' to see all references
```
I get no errors when using zig build with 0.14.1
Kind regards.

**Comment by MoAlyousef** [comment]
I’ve migrated the codebase to zig 0.15.1. There are some breaking changes due to zig removing usingnamespace.
